### ISSUE TITLE
Change location of GitHub Actions

### ISSUE THREAD

**Issue by bartekpacia** [leancodepl/mobile-tools#35]
Currently, we have one composite GitHub Action ([pub-release](https://github.com/leancodepl/mobile-tools/blob/master/.github/actions/pub-release/action.yaml)), but I expect that as the time will pass, a few more might appear. We can help the community by creating high-quality workflows.

## Problem

The problem with the current location of that action is that it's long and ugly. Just look at this:

```yaml
steps:
  # ...
  - name: Publish to pub.dev
    uses: leancodepl/mobile-tools/.github/actions/pub-release@pub-release-v1
```

It's both too long, and the version is redundant with the action name.

### Actions in `mobile-tools`

Wouldn't it be better if we could use that action like:

```yaml
steps:
  # ...
  - name: Publish to pub.dev
    uses: leancodepl/mobile-tools/pub-release@v1
```

Pros:
- we keep everything in a single repo

Cons:
- versions of GitHub Actions are tied with versions of small mobile tooling scripts in `bin`.
- repo layout becomes kinda ugly. Action directories reside next to the `bin` directory:

  ```
  ├── LICENSE
  ├── README.md
  ├── bin
  │   ├── echo_changelog
  │   ├── generate_keystore
  │   ├── is_prerelease
  │   └── link_changelog
  ├── patrol-setup
  │   └── action.yaml
  └── pub-release
      └── action.yaml
  ```

### Actions in a separate `actions` repo

```yaml
steps:
  # ...
  - name: Publish to pub.dev
    uses: leancodepl/actions/pub-release@v1
```

or, in the future:

```yaml
steps:
  # ...
  - name: Publish to pub.dev
    uses: leancodepl/actions/setup-patrol@v1
```

This implies that all actions are versioned together. It may seem bizarre at first, but it appears to work fine in practice. A good example is the [github/codeql-action](https://github.com/github/codeql-action) repo.

Pros:
- looks _lean_
- Think like this: if you use an action from `leancodepl/action`, you should know it's good and reliable.

Cons:
- another repo
